// replace double quotes with &#34; in strings
// replace single quotes with &#39; in strings

var movie = new Array;
movie[0] = {
	id: "0",
	title: "101 Dalmations",
	date: "1961",
	description: "When a litter of dalmatian puppies are abducted by the minions of Cruella De Vil, the parents must find them before she uses them for a diabolical fashion statement.",
	storyline: "Pongo is a male Dalmatian living in London with his master, Roger, a bachelor songwriter who has yet to sell his first tune. Bored with their single existence, Pongo arranges for Roger to meet Anita, a pretty young woman who just happens to have a female Dalmatian named Perdita. It is not long before love blossoms all around and a double wedding takes place. A few months later, Perdita gives birth to 15 puppies, much to the delight of Cruella De Vil, a wealthy, wicked former schoolmate of Anita's whose burning passion is to own a coat made of Dalmatian pelts. When she is unable to purchase the puppies, she has them &#34;dognapped&#34; and brought to her crumbling estate in the country, where 84 other Dalmatians are also being held captive. All attempts by the police to find the missing pups fail, and the desperate Pongo and Perdita appeal to the dogs of London, via the &#34;twilight bark.&#34; Led by The Colonel, an indomitable shaggy dog and a cat named Sergeant Tibbs, all dogdom comes to the rescue and, aided by geese, cows, and horses, tracks down the missing puppies.",
	runtime: "79 min",
	director: "Clyde Geronimi, Hamilton Luske",
	star1: "Rod Taylor",
	star1_link: "http://www.imdb.com/name/nm0001792/",
	star2: "Betty Lou Gerson",
	star2_link: "http://www.imdb.com/name/nm0314867/",
	star3: "J. Pat O'Malley",
	star3_link: "http://www.imdb.com/name/nm0641729/",
	image: "101_dalmations.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family",
	gross: "$143,992,148 (USA)",
	box_rank: "12",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/8TG1rc9c38I"
	};
movie[1] = {
	id: "1",
	title: "A Bug&#39;s Life",
	date: "1998",
	description: "A misfit ant, looking for &#34;warriors&#34; to save his colony from greedy grasshoppers, recruits a group of bugs that turn out to be an inept circus troupe.",
	storyline: "Every year, a bunch of grasshoppers come to the anthill and eat what the ants have gathered for them. The &#34;offering&#34;, as the ants call the ritual, is a part of their fate. One day in spring, when the offering's preparation has just been finished, Flik, unliked inventor ant, accidentally drops the whole offered seeds into the river. The grasshoppers come and give the ants a second chance to collect food until fall. Flik sets off to find bugs that are willing to fight the grasshoppers (nobody expects him to succeed anyway) and, due to a double misinterpretation, returns with a circus crew, giving everybody new hope. When the misunderstanding finally gets cleared out, there is only little time left for a new plan, which has to work, or else...",
	runtime: "95 min",
	director: "John Lasseter, Andrew Stanton",
	star1: "Kevin Spacey",
	star1_link: "http://www.imdb.com/name/nm0000228/",
	star2: "Dave Foley",
	star2_link: "http://www.imdb.com/name/nm0004929/",
	star3: "Julia Louis-Dreyfus",
	star3_link: "http://www.imdb.com/name/nm0000506/",
	image: "a_bugs_life.jpg",
	rating: "G",
	genre: "Animation, Adventure, Comedy, Family",
	gross: "$162,798,565 (USA)",
	box_rank: "10",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/vhGlMv3UCXA"
	};
movie[2] = {
	id: "2",
	title: "Alice In Wonderland",
	date: "1951",
	description: "Alice stumbles into the world of Wonderland. Will she get home? Not if the Queen of Hearts has her way.",
	storyline: "On a golden afternoon, young Alice follows a White Rabbit, who disappears down a nearby rabbit hole. Quickly following him, she tumbles into the burrow - and enters the merry, topsy-turvy world of Wonderland! Memorable songs and whimsical escapades highlight Alice's journey, which culminates in a madcap encounter with the Queen of Hearts - and her army of playing cards!",
	runtime: "75 min",
	director: "Clyde Geronimi, Wilfred Jackson",
	star1: "Kathryn Beaumont",
	star1_link: "http://www.imdb.com/name/nm0064607/",
	star2: "Ed Wynn",
	star2_link: "http://www.imdb.com/name/nm0943956/",
	star3: "Richard Haydn",
	star3_link: "http://www.imdb.com/name/nm0370821/",
	image: "alice_in_wonderland.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family, Fantasy, Musical",
	gross: "$3,000,000 (Budget)",
	box_rank: "18",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/KLIqErnQCuw"
	};
movie[3] = {
	id: "3",
	title: "Aladdin",
	date: "1992",
	description: "Aladdin, a street urchin, accidentally meets Princess Jasmine, who is in the city undercover. They love each other, but she can only marry a prince.",
	storyline: "Aladdin is a street-urchin who lives in a large and busy town long ago with his faithful monkey friend Abu. When Princess Jasmine gets tired of being forced to remain in the palace that overlooks the city, she sneaks out to the marketplace, where she accidentally meets Aladdin. Under the orders of the evil Jafar (the sultan's advisor), Aladdin is thrown in jail and becomes caught up in Jafar's plot to rule the land with the aid of a mysterious lamp. Legend has it that only a person who is a &#34;diamond in the rough&#34; can retrieve the lamp from the Cave of Wonders. Aladdin might fit that description, but that's not enough to marry the princess, who must (by law) marry a prince.",
	runtime: "90 min",
	director: "Ron Clements, John Musker",
	star1: "Scott Weinger",
	star1_link: "http://www.imdb.com/name/nm0918334/",
	star2: "Robin Williams",
	star2_link: "http://www.imdb.com/name/nm0000245/",
	star3: "Linda Larkin",
	star3_link: "http://www.imdb.com/name/nm0488306/",
	image: "aladdin.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family, Fantasy, Musical, Romance",
	gross: "$504,050,219 (Worldwide)",
	box_rank: "3",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/_SHlwJmL1jY"
	};
movie[4] = {
	id: "4",
	title: "AristoCats, The",
	date: "1970",
	description: "With the help of a smooth talking tomcat, a family of Parisian felines set to inherit a fortune from their owner try to make it back home after a jealous butler kidnaps them and leaves them in the country.",
	storyline: "Retired madame Adelaide Bonfamille enjoys the good life in her Paris villa with even classier cat Duchess and three kittens: pianist Berlioz, painter Toulouse and sanctimonious Marie. When loyal butler Edgar overhears her will leaves everything to the cats until their death, he drugs and kidnaps them. However retired army dogs make his sidecar capsize on the country. Crafty stray cat Thomas O'Malley takes them under his wing back to Paris. Edgar tries to cover his tracks and catch them at return, but more animals turn on him, from the cart horse Frou-Frou to the tame mouse Roquefort and O'Malley's jazz friends.",
	runtime: "78 min",
	director: "Wolfgang Reitherman",
	star1: "Phill Harris",
	star1_link: "http://www.imdb.com/name/nm0365201/",
	star2: "Eva Gabor",
	star2_link: "http://www.imdb.com/name/nm0001247/",
	star3: "Sterling Holloway",
	star3_link: "http://www.imdb.com/name/nm0001359/",
	image: "aristocats.jpg",
	rating: "G",
	genre: "Animation, Adventure, Comedy, Family, Musical",
	gross: "$18,000,000 (USA)",
	box_rank: "17",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/223bYlLJSnU"
	}; 
movie[5] = {
	id: "5",
	title: "Beauty and the Beast",
	date: "1991",
	description: "Belle, whose father is imprisoned by the Beast, offers herself instead and discovers her captor to be an enchanted prince.",
	storyline: "Prince Adam was cursed to a beast form by Enchantress who saw no love in his arrogant heart for others. The one way he could break the spell was to learn to love another and earn her love in return before the last petal from his enchanted rose fell, which would bloom until his twenty-first birthday. But who could ever learn to love a beast? Ten years later, Maurice, an inventor from a nearby village, becomes lost in the woods and seeks shelter in the Beast's castle, the Beast imprisons him for trespassing. His daughter Belle, a bookworm who dreams of life outside her provincial village, finds him trapped in the castle and offers her place in his stead. The Beast accepts with a promise she'll remain in the castle forever. In the beginning Belle views him as nothing more than a monster, he views her as difficult and stubborn. But the two soon taste the bitter-sweetness of finding you can change and learning you were wrong.",
	runtime: "84 min",
	director: "Gary Trousdale, Kirt Wise",
	star1: "Paige O'Hara",
	star1_link: "http://www.imdb.com/name/nm0641314/",
	star2: "Robby Benson",
	star2_link: "http://www.imdb.com/name/nm0000913/",
	star3: "Richard White",
	star3_link: "http://www.imdb.com/name/nm0925369/",
	image: "beauty_and_the_beast.jpg",
	rating: "G",
	genre: "Animation, Family, Fantasy, Musical, Romance",
	gross: "$347,900,000 (Worldwide)",
	box_rank: "5",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/tRlzmyveDHE"
	};
movie[6] = {
	id: "6",
	title: "Brave Little Toaster, The",
	date: "1987",
	description: "A toaster, a blanket, a lamp, a radio, and a vacuum cleaner journey to the city to find their master after being abandoned in their cabin in the woods.",
	storyline: "When a young boy and his family go on holiday, their household appliances, led by the toaster, think they've been abandoned. They decide, rather than be left alone in the house for who knows how long, to try to find him. So begins a dangerous and amusing venture through the city and countryside. This should read: When a young boy and his family don't come one year to their holiday home, their household appliances, led by the toaster think their master might be in trouble. They decided that rather than stay where they are, they'll try to find them. So beings a dangerous and amusing adventure through the countryside and into the big city.",
	runtime: "90 min",
	director: "Jerry Rees",
	star1: "Jon Lovitz",
	star1_link: "http://www.imdb.com/name/nm0001484/",
	star2: "Timothy Stack",
	star2_link: "http://www.imdb.com/name/nm0821048/",
	star3: "Timothy Day",
	star3_link: "http://www.imdb.com/name/nm0206610/",
	image: "brave_little_toaster.jpg",
	rating: "NR",
	genre: "Animation, Adventure, Comedy, Family, Fantasy, Musical",
	gross: "$2,300,000 (budget)",
	box_rank: "19",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/rlpDZ5-xwLg"
	};
movie[7] = {
	id: "7",
	title: "Cars",
	date: "2006",
	description: "A hot-shot race-car named Lightning McQueen gets waylaid in Radiator Springs, where he finds the true meaning of friendship and family.",
	storyline: "Lightning McQueen is a young, hotshot rookie race car in the last race of the season. At the end of the race, he finds out he is tied with Chick Hicks and The King. On the way to the tie-breaker race in Los Angeles, California, some hot punk cars get him lost in a little town called Radiator Springs on the old Route 66 road, which has been long forgotten many years ago. Scared to death, he tears up the town's main road and is sentenced to community service by Doc Hudson. During this time, he meets a funny, but lovable tow truck named Mater and a beautiful Porsche Carrera named Sally. He also meets some other cars, whom which he finds to be quite odd. All he wants to do is get out of this town and back into the big city, but as the week until the race goes on, the town folk help him discover that life isn't just about trophies, fame, and sponsorships and McQueen learns about family and friendship.",
	runtime: "117 min",
	director: "John Lasseter, Joe Ranft",
	star1: "Owen Wilson",
	star1_link: "http://www.imdb.com/name/nm0005562/",
	star2: "Bonnie Hunt",
	star2_link: "http://www.imdb.com/name/nm0001372/",
	star3: "Paul Newman",
	star3_link: "http://www.imdb.com/name/nm0000056/",
	image: "cars.jpg",
	rating: "G",
	genre: "Animation, Adventure, Comedy, Family, Sport",
	gross: "$461,981,126 (Worldwide)",
	box_rank: "4",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/JzwWqkxBb5I"
	};
movie[8] = {
	id: "8",
	title: "Cars 2",
	date: "2011",
	description: "Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.",
	storyline: "Star race car Lightning McQueen and his pal Mater head overseas to compete in the World Grand Prix race. But the road to the championship becomes rocky as Mater gets caught up in an intriguing adventure of his own: international espionage.",
	runtime: "106 min",
	director: "John Lasseter, Brad Lewis",
	star1: "Owen Wilson",
	star1_link: "http://www.imdb.com/name/nm0005562/",
	star2: "Larry the Cable Guy",
	star2_link: "http://www.imdb.com/name/nm1249256/",
	star3: "Michael Caine",
	star3_link: "http://www.imdb.com/name/nm0000323/",
	image: "cars_2.jpg",
	rating: "G",
	genre: "Animation, Action, Adventure, Comedy, Family",
	gross: "$191,450,875 (USA)",
	box_rank: "8",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/oFTfAdauCOo"
	};
movie[9] = {
	id: "9",
	title: "Fox and the Hound, The",
	date: "1981",
	description: "Two childhood animal friends find themselves forced to become enemies.",
	storyline: "A fox named Tod and a hound named Copper become such good friends and they play together. But Copper's owner, Amos Slade, wants to kill Tod and he'll do anything to get him. He even has his other dog Chief to help him. As Tod and Copper get older they start to become more of enemies. Will they ever get their friendship back?",
	runtime: "83 min",
	director: "Ted Berman, Richard Rich",
	star1: "Mickey Rooney",
	star1_link: "http://www.imdb.com/name/nm0001682/",
	star2: "Kurt Russell",
	star2_link: "http://www.imdb.com/name/nm0000621/",
	star3: "Pearl Bailey",
	star3_link: "http://www.imdb.com/name/nm0047440/",
	image: "fox_and_the_hound.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family",
	gross: "$43,899,231 (USA)",
	box_rank: "16",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/JuMSx0RvgBk"
	};
movie[10] = {
	id: "10",
	title: "Hercules",
	date: "1997",
	description: "The son of the Greek Gods Zeus and Hera is stripped of his immortality as an infant and must become a true hero in order to reclaim it.",
	storyline: "After Zeus fights and sends the Titans to the underworld, he becomes the ruler of Mount Olympus, home of all greek gods. Hades is sent to rule the underworld, but he makes plans to throw Zeus out of Mount Olympus with the Titans' help. The three Fates warn him that his plans would be endangered if Hercules, Zeus newborn child, is still around by the time he tries to take over Mount Olympus. Hades sends Pain and Panic to turn Hercules into a mortal and kill him, but they fail in their attempt and leave him on earth with his divine strength to be raised as a human. Hercules grows up but later learns he is the son of gods, and in order to return to Mt. Olympus he must turn into a &#34;true hero&#34;. He is trained by Phil the satyr and becomes the most famous hero in ancient Greece after battling monsters of all kinds. He even saves Mt. Olympus from Hade's take-over, but he only becomes a god again after he offers to exchange his life in order to save Meg, his love, from Hades' underworld and shows that a true hero must have a strong heart and not only physical strength.",
	runtime: "93 min",
	director: "Ron Clements, John Musker",
	star1: "Tate Donovan",
	star1_link: "http://www.imdb.com/name/nm0004883/",
	star2: "Susan Egan",
	star2_link: "http://www.imdb.com/name/nm0250743/",
	star3: "James Woods",
	star3_link: "http://www.imdb.com/name/nm0000249/",
	image: "hercules.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family, Fantasy, Musical, Romance",
	gross: "$146,000,000 (Worldwide)",
	box_rank: "11",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/=Y5J8jie6tgk"
	};
movie[11] = {
	id: "11",
	title: "Incredibles, The",
	date: "2004",
	description: "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.",
	storyline: "Fifteen years ago, superheroes walked the streets of Metroville, performing acts of great heroism and inspiring many to follow their example. But a string of lawsuits by disgruntled people they'd helped lead to political and public outcry, and the Supers were forced into retirement and government-funded anonymity. Bob Parr used to be Mr. Incredible, one of the greatest and strongest Supers; now, he lives a mundane life as a suburban insurance agent. Although his wife Helen (formerly Elastigirl) has moved on and is more concerned with raising their children Dashiell (who is super-fast and super-confident), Violet (who can turn invisible - and is super-shy) and baby Jack-Jack than battling evil, Bob still yearns for the good old days - and his chance comes when he is approached by a shadowy government organization and asked to join their numbers. But all is not as it seems, and Bob will find himself trapped by Syndrome, an embittered enemy who in his youth once idolized Mr. Incredible - and only his family will be able to save him now...",
	runtime: "115 min",
	director: "Brad Bird",
	star1: "Craig T. Nelson",
	star1_link: "http://www.imdb.com/name/nm0005266/",
	star2: "Samuel L. Jackson",
	star2_link: "http://www.imdb.com/name/nm0000168/",
	star3: "Holly Hunter",
	star3_link: "http://www.imdb.com/name/nm0000456/",
	image: "incredibles.jpg",
	rating: "PG",
	genre: "Animation, Action, Adventure, Family, Fantasy",
	gross: "$631,442,092 (Worldwide)",
	box_rank: "2",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/=1LASc8ewLaw"
	};
movie[12] = {
	id: "12",
	title: "Jungle Book, The",
	date: "1967",
	description: "Bagheera the Panther and Baloo the Bear have a difficult time trying to convince a boy to leave the jungle for human civilization.",
	storyline: "Mowgli is a boy who has been raised by wolves in the Indian jungle. When the wolves hear that the fierce tiger, Shere Kahn, is nearby, they decide to send Mowgli to a local &#34;man tribe&#34;. On his way to the village, Mowgli meets many animal characters in this musical tale. When Shere Kahn learns of Mowgli's presence, he tracks him down.",
	runtime: "78 min",
	director: "Wolfgang Reitherman",
	star1: "Phil Harris",
	star1_link: "http://www.imdb.com/name/nm0365201/",
	star2: "Sebastian Cabot",
	star2_link: "http://www.imdb.com/name/nm0001982/",
	star3: "Louis Prima",
	star3_link: "http://www.imdb.com/name/nm0697515/",
	image: "the_jungle_book.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family, Musical",
	gross: "$205,800,000 (Worldwide)",
	box_rank: "7",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/7inbFKJOy_E"
	};
movie[13] = {
	id: "13",
	title: "Kung Fu Panda",
	date: "2008",
	description: "In the Valley of Peace, Po the Panda finds himself chosen as the Dragon Warrior despite the fact that he is obese and a complete novice at martial arts.",
	storyline: "It's the story about a lazy, irreverent slacker panda, named Po, who is the biggest fan of Kung Fu around...which doesn't exactly come in handy while working every day in his family's noodle shop. Unexpectedly chosen to fulfill an ancient prophecy, Po's dreams become reality when he joins the world of Kung Fu and studies alongside his idols, the legendary Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- under the leadership of their guru, Master Shifu. But before they know it, the vengeful and treacherous snow leopard Tai Lung is headed their way, and it's up to Po to defend everyone from the oncoming threat. Can he turn his dreams of becoming a Kung Fu master into reality? Po puts his heart - and his girth - into the task, and the unlikely hero ultimately finds that his greatest weaknesses turn out to be his greatest strengths.",
	runtime: "90 min",
	director: "Mark Osborne, John Stevenson",
	star1: "Jack Black",
	star1_link: "http://www.imdb.com/name/nm0085312/",
	star2: "Ian McShane",
	star2_link: "http://www.imdb.com/name/nm0574534/",
	star3: "Angelina Jolie",
	star3_link: "http://www.imdb.com/name/nm0001401/",
	image: "kung_fu_panda.jpg",
	rating: "PG",
	genre: "Animation, Action, Adventure, Comedy, Family",
	gross: "$165,230,261 (USA)",
	box_rank: "9",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/VgU1Ayn2Cg8"
	};
movie[14] = {
	id: "14",
	title: "Kung Fu Panda 2",
	date: "2011",
	description: "Po and his friends fight to stop an peacock villain from conquering China with a deadly new weapon, but the Dragon Warrior must come to terms with his past.",
	storyline: "In the Valley of Peace, Po Ping is revelling in his fulfilled dreams as he serves as the fabled Dragon Warrior protecting his home with his heroes now his closest friends. However, Po and company learn that the murderous Lord Shen of Gongman City is threatening the land with a fearsome new weapon that could mean the end of kung fu. They attempt to stop him, but the panda is burdened with crippling memory flashbacks linked to this villain. Now with China in the balance, Po must learn about his past and find true inner peace against all opposition.",
	runtime: "91 min",
	director: "Jennifer Yuh",
	star1: "Jack Black",
	star1_link: "http://www.imdb.com/name/nm0085312/",
	star2: "Angelina Jolie",
	star2_link: "http://www.imdb.com/name/nm0001401/",
	star3: "Jackie Chan",
	star3_link: "http://www.imdb.com/name/nm0000329/",
	image: "kung_fu_panda_2.jpg",
	rating: "PG",
	genre: "Animation, Action, Adventure, Comedy, Family",
	gross: "$631,744,560 (Worldwide)",
	box_rank: "1",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/7GHT-TSiZio"
	};
movie[15] = {
	id: "15",
	title: "Lady and the Tramp",
	date: "1955",
	description: "The romantic tale of a sheltered uptown Cocker Spaniel dog and a streetwise downtown Mutt.",
	storyline: "Lady is a pampered Cocker Spaniel who lives in the ritzy part of town. Everything is great until Jim Dear and Darling, Lady's owners have a baby. Then Aunt Sarah and her two scheming Siamese cats come to stay. Lady is thought to be vicious and is muzzled and put outside. Tramp comes to her rescue. Lady runs away with him only to be caught by the dogcatcher.",
	runtime: "76 min",
	director: "Clyde Geronimi, Wilfred Jackson",
	star1: "Barbara Luddy",
	star1_link: "http://www.imdb.com/name/nm0524853/",
	star2: "Larry Roberts",
	star2_link: "http://www.imdb.com/name/nm0731333/",
	star3: "Peggy Lee",
	star3_link: "http://www.imdb.com/name/nm0498007/",
	image: "lady_and_the_tramp.jpg",
	rating: "G",
	genre: "Animation, Family, Music, Romance",
	gross: "$93,600,000 (USA)",
	box_rank: "14",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/LZmVm6qv1Lk"
	};
movie[16] = {
	id: "16",
	title: "Lion King, The",
	date: "1994",
	description: "Tricked into thinking he killed his father, a guilt ridden lion cub flees into exile and abandons his identity as the future King.",
	storyline: "A lion prince is born in Africa and is told by his father, King Mufasa, that when Mufasa dies, Simba will take over the throne, cheating his Uncle Scar out of becoming King of the Pride Lands. Scar, fueled by rage, plots to kill Mufasa and Simba so he is able to take over the throne. He and the hyenas team up and manage to push Mufasa to his death, but Simba survives, and, armed with misinformation, flees the Pride Lands. Simba, believing that his father's death was his own fault, decides to never return home; due to this decision, he meets Timone the Meerkat, and Pummba the Warthog, and the trio become fast friends. Simba stays with them well into adulthood until his childhood friend, Nala, tracks him down and begs him to return to the Pride Lands, where Scar has reigned as King for years, and ruined everything. All of the animals will starve to death if Simba does not return. Simba eventually agrees to fight for his kingdom after learning that Mufasa's death was not his fault after all. Simba battles Scar, ready to claim the throne and complete &#34;The Circle of Life.&#34;",
	runtime: "89 min",
	director: "Roger Allers, Rob Minkoff",
	star1: "Matthew Broderick",
	star1_link: "http://www.imdb.com/name/nm0000111/",
	star2: "Jeremy Irons",
	star2_link: "http://www.imdb.com/name/nm0000460/",
	star3: "James Earl Jones",
	star3_link: "http://www.imdb.com/name/nm0000469/",
	image: "the_lion_king.jpg",
	rating: "G",
	genre: "Animation, Adventure, Comedy, Drama, Family, Musical",
	gross: "$945,578,747 (Worldwide)",
	box_rank: "0",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/4sj1MT05lAA"
	};
movie[17] = {
	id: "17",
	title: "Little Mermaid, The",
	date: "1989",
	description: "A mermaid princess makes a faustian bargain with an unscrupulous seahag in order to meet a human prince on land.",
	storyline: "Loosely based upon the story by Hans Christian Andersen. Ariel, youngest daughter of King Triton, is dissatisfied with life in the sea. She longs to be with the humans above the surface, and is often caught in arguments with her father over those &#34;barbaric fish-eaters&#34;. She goes to meet Ursula, the Sea Witch, to strike a deal, but Ursula has bigger plans for this mermaid and her father.",
	runtime: "83 min",
	director: "Ron Clements, John Musker",
	star1: "Jodi Benson",
	star1_link: "http://www.imdb.com/name/nm0072533/",
	star2: "Samuel E. Wright",
	star2_link: "http://www.imdb.com/name/nm0942789/",
	star3: "Rene Auberjonois",
	star3_link: "http://www.imdb.com/name/nm0041281/",
	image: "the_little_mermaid.jpg",
	rating: "G",
	genre: "Animation, Family, Fantasy, Musical, Romance",
	gross: "$109,859,444 (USA)",
	box_rank: "13",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/ZGZX5-PAwR8"
	};
movie[18] = {
	id: "18",
	title: "Monsters, Inc.",
	date: "2001",
	description: "Monsters generate their city's power by scaring children, but they are terribly afraid themselves of being contaminated by children, so when one enters Monstropolis, top scarer Sulley finds his world disrupted.",
	storyline: "In a city of monsters with no humans called Monstropolis centers around Monsters, Inc., the city's power company. Monsters, Inc. The lovable confidant, tough large, furry blue behemoth-like giant monster named James P. Sullivan (A.K.A. better known as Sulley) and his Cyclops wisecracking best friend short, green monster with one large eye, Mike Wazowski discover what happens when the real world interacts with theirs in the form of a 2-year-old baby girl dubbed &#34;Boo,&#34; who accidentally sneaks into the monster world with Sulley one night. And now it's up to Sulley and Mike to send Boo back in her door before anybody and especially two evil villains such as Sulley's main rival as a scarer chameleon-like Randall(a monster that Boo is very afraid of), who possesses the ability to change the color of his skin and Mike and Sulley's boss Mr. Waternoose the chairman and chief executive officer of Monsters, Inc.",
	runtime: "92 min",
	director: "Pete Docter, David Silverman",
	star1: "Billy Crystal",
	star1_link: "http://www.imdb.com/name/nm0000345/",
	star2: "John Goodman",
	star2_link: "http://www.imdb.com/name/nm0000422/",
	star3: "Mary Gibbs",
	star3_link: "http://www.imdb.com/name/nm0316701/",
	image: "monsters_inc.jpg",
	rating: "G",
	genre: "Animation, Adventure, Comedy, Family, Fantasy",
	gross: "$255,870,172 (USA)",
	box_rank: "6",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/cvOQeozL4S0"
	};
movie[19] = {
	id: "19",
	title: "Peter Pan",
	date: "1953",
	description: "Wendy and her brothers are whisked away to the magical world of Neverland with the hero of their stories, Peter Pan.",
	storyline: "Based upon Sir James M. Barrie's 1904 play about the boy who refuses to grow up, the film begins in the London nursery of Wendy, John, and Michael Darling, where three children are visited by Peter Pan. With the help of his tiny friend, the fairy Tinkerbell, Peter takes the three children on a magical flight to Never Land. This enchanted island is home to Peter, Tink, the Lost Boys, Tiger Lily and her Native American nation, and the scheming Captain Hook who is as intent on defeating Peter Pan as he is from escaping the tick-tocking crocodile that once ate a hand of his that Peter Pan cut off--and loved the taste of so much.",
	runtime: "77 min",
	director: "Clyde Geronimi, Wilfred Jackson",
	star1: "Bobby Driscoll",
	star1_link: "http://www.imdb.com/name/nm0237985/",
	star2: "Kathryn Beaumont",
	star2_link: "http://www.imdb.com/name/nm0064607/",
	star3: "Hans Conried",
	star3_link: "http://www.imdb.com/name/nm0175788/",
	image: "peter_pan.jpg",
	rating: "G",
	genre: "Animation, Adventure, Family, Fantasy, Music",
	gross: "$87,400,000 (USA)",
	box_rank: "15",
	oa_rank: "",
	trailer: "http://www.youtube.com/embed/4GVdbBpVVoc"
	};	
/*	
movie[] = {
	id: "",
	title: "",
	date: "",
	description: "",
	storyline: "",
	runtime: "",
	director: "",
	star1: "",
	star1_link: "",
	star2: "",
	star2_link: "",
	star3: "",
	star3_link: "",
	image: "",
	rating: "",
	genre: "",
	gross: "",
	box_rank: "",
	oa_rank: "",
	trailer: ""
	};	
*/	

/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/

var new_theatre = new Array;
new_theatre[0] = {
	id: "0",
	title: "Arthur Christmas",
	date: "2011",
	date_r: "23 November",
	storyline: "Arthur Christmas reveals the incredible, never-before seen answer to every child's question: 'So how does Santa deliver all those presents in one night?' The answer: Santa's exhilarating, ultra-high-tech operation hidden beneath the North Pole. But at the center of the film is a story about a family in a state of comic dysfunction and an unlikely hero, Arthur, with an urgent mission that must be completed before Christmas morning dawns.",
	runtime: "97 min",
	director: "Sarah Smith, Barry Cook",
	star1: "James McAvoy",
	star1_link: "http://www.imdb.com/name/nm0564215/",
	star2: "Jim Broadbent",
	star2_link: "http://www.imdb.com/name/nm0000980/",
	star3: "Bill Nighy",
	star3_link: "http://www.imdb.com/name/nm0631490/",	
	rating: "PG",
	genre: "Animation, Comedy, Drama, Family",
	image: "arthur_christmas",
	trailer: "http://www.youtube.com/embed/7tk-WZSqIGQ"
	};
new_theatre[1] = {
	id: "1",
	title: "Hugo",
	date: "2011",
	date_r: "23 November",
	storyline: "Hugo is an orphan boy living in the walls of a train station in the 1930s in Paris. He fixes clocks and other gadgets as he learned to from his father and uncle. The only thing that he has left that connects him to his father is an automaton that doesn't work; Hugo has to find its heart-shaped key. On his adventures, he meets with a cranky old man who works in the train station and his adventure-seeking god-daughter. Hugo finds that they have a surprising connection to his father and the automaton, and as he discovers it, the old man starts remembering his past and his significance to the world of film-making.",
	runtime: "126 min",
	director: "Martin Scorsese",
	star1: "Asa Butterfield",
	star1_link: "http://www.imdb.com/name/nm2633535/",
	star2: "Chloe Grace Moretz",
	star2_link: "http://www.imdb.com/name/nm1631269/",
	star3: "Christopher Lee",
	star3_link: "http://www.imdb.com/name/nm0000489/",	
	rating: "PG",
	genre: "Adventure, Drama, Family, Fantasy, Mystery",
	image: "hugo",
	trailer: "http://www.youtube.com/embed/hR-kP-olcpM"
	};
new_theatre[2] = {
	id: "2",
	title: "Muppets, The",
	date: "2011",
	date_r: "23 November",
	storyline: "When 3 muppet fans learn that Tex Richman wants to drill under the muppet theater for oil Gary, Mary and Walter set out to find the muppets who have been split up for years Kermit lives in his own mansion depressed in hollywood, Gonzo is a high class plumber at Gonzo's Royal Flush, Fozzie performs with a tribute band called The Moopets , Miss Piggy is the plus-size fashion editor at Vogue Paris, and Animal is at a celebrity anger managment rehab center in Santa Barbara.",
	runtime: "103 min",
	director: "James Bobin",
	star1: "Amy Adams",
	star1_link: "http://www.imdb.com/name/nm0010736/",
	star2: "Jason Segal",
	star2_link: "http://www.imdb.com/name/nm0781981/",
	star3: "Chris Cooper",
	star3_link: "http://www.imdb.com/name/nm0177933/",	
	rating: "PG",
	genre: "Comedy, Drama, Family, Musical",
	image: "the_muppets",
	trailer: "http://www.youtube.com/embed/IaeXrigYkGY"
	};
new_theatre[3] = {
	id: "3",
	title: "Alvin and the Chipmunks: Chipwrecked",
	date: "2011",
	date_r: "16 December",
	storyline: "Playing around while aboard a cruise ship, the Chipmunks and Chipettes accidentally go overboard and end up marooned in a tropical paradise. They discover their new turf is not as deserted as it seems.",
	runtime: "87 min",
	director: "Mike Mitchell",
	star1: "Justin Long",
	star1_link: "http://www.imdb.com/name/nm0519043/",
	star2: "Matthew Gray Gubler",
	star2_link: "http://www.imdb.com/name/nm1693763/",
	star3: "Jesse McCartney",
	star3_link: "http://www.imdb.com/name/nm0565366/",	
	rating: "G",
	genre: "Animation, Comedy, Family, Fantasy, Music",
	image: "alvin_and_the_chipmunks",
	trailer: "http://www.youtube.com/embed/kKJ7kDLd2o8"
	};
new_theatre[4] = {
	id: "4",
	title: "Dr. Seuss&#39; The Lorax",
	date: "2012",
	date_r: "02 March",
	storyline: "A 12-year-old boy searches for the one thing that will enable him to win the affection of the girl of his dreams. To find it he must discover the story of the Lorax, the grumpy yet charming creature who fights to protect his world.",
	runtime: "94 min",
	director: "Chris Renaud, Kyle Balda",
	star1: "Zac Efron",
	star1_link: "http://www.imdb.com/name/nm1374980/",
	star2: "Taylor Swift",
	star2_link: "http://www.imdb.com/name/nm2357847/",
	star3: "Danny Devito",
	star3_link: "http://www.imdb.com/name/nm0000362/",	
	rating: "PG",
	genre: "Action, Family, Fantasy",
	image: "the_lorax",
	trailer: "http://www.youtube.com/embed/Gs_Em1XvAiU"
	};
new_theatre[5] = {
	id: "5",
	title: "Madagascar 3: Europe&#39;s Most Wanted",
	date: "2012",
	date_r: "08 June",
	storyline: "Alex the Lion, Marty the Zebra, Melman the Giraffe and Gloria the Hippo join a traveling circus in an effort to get back home to New York.",
	runtime: "Unknown",
	director: "Eric Darnell",
	star1: "Ben Stiller",
	star1_link: "http://www.imdb.com/name/nm0001774/",
	star2: "Jada Pinkett Smith",
	star2_link: "http://www.imdb.com/name/nm0000586/",
	star3: "Chris Rock",
	star3_link: "http://www.imdb.com/name/nm0001674/",	
	rating: "Unknown",
	genre: "Animation, Adventure, Comedy",
	image: "madagascar_3",
	trailer: "http://www.youtube.com/embed/5LhVYKfqZyA"
	};
	
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/

var new_dvd = new Array;
new_dvd[0] = {
	id: 		"0",
	title:		"Hoodwinked Too! Hood vs. Evil",
	date:		"16 August 2011",
	image:		"hoodwinked",
	dvd: 		"http://www.amazon.com/Hoodwinked-Too-Hood-vs-Evil/dp/B0052XI5J8/ref=sr_1_2?s=movies-tv&ie=UTF8&qid=1328577057&sr=1-2",
	bluray: 	"http://www.amazon.com/Hoodwinked-Hood-Two-Disc-Blu-ray-Combo/dp/B0052XI5HK/ref=sr_1_4?s=movies-tv&ie=UTF8&qid=1328577057&sr=1-4"
	}
new_dvd[1] = {
	id: 		"1",
	title:		"Mars Needs Moms",
	date:		"09 August 2011",
	image:		"mars",
	dvd: 		"http://www.amazon.com/Mars-Needs-Moms-Joan-Cusack/dp/B004EPZ048/ref=sr_1_1?s=movies-tv&ie=UTF8&qid=1328577200&sr=1-1",
	bluray: 	"http://www.amazon.com/Mars-Needs-Two-Disc-Blu-ray-Combo/dp/B004EPZ04I/ref=sr_1_2?s=movies-tv&ie=UTF8&qid=1328577200&sr=1-2"
	}
new_dvd[2] = {
	id: 		"2",
	title:		"Rio",
	date:		"02 August 2011",
	image:		"rio",
	dvd: 		"http://www.amazon.com/Rio-Jesse-Eisenberg/dp/B004HO6I4M/ref=sr_1_1?s=movies-tv&ie=UTF8&qid=1328577256&sr=1-1",
	bluray: 	"http://www.amazon.com/Rio-Blu-ray-Combo-Digital-Copy/dp/B004HO6I4W/ref=sr_1_2?s=movies-tv&ie=UTF8&qid=1328577256&sr=1-2"
	}
new_dvd[3] = {
	id: 		"0",
	title:		"Rango",
	date:		"15 July 2011",
	image:		"rango",
	dvd: 		"http://www.amazon.com/Rango-Johnny-Depp/dp/B003Y5H53S/ref=sr_1_1?ie=UTF8&qid=1328575786&sr=8-1",
	bluray: 	"http://www.amazon.com/Rango-Two-Disc-Blu-ray-Combo-Digital/dp/B003Y5H542/ref=sr_1_2?ie=UTF8&qid=1328575786&sr=8-2"
	}
new_dvd[4] = {
	id: 		"4",
	title:		"Gnomeo & Juliet",
	date:		"24 May 2011",
	image:		"gnomeo",
	dvd: 		"http://www.amazon.com/Gnomeo-Juliet-James-McAvoy/dp/B004HO6HXY/ref=sr_1_1?s=movies-tv&ie=UTF8&qid=1328577316&sr=1-1",
	bluray: 	"http://www.amazon.com/Gnomeo-Juliet-Two-Disc-Blu-ray-Combo/dp/B004HO6HY8/ref=sr_1_2?s=movies-tv&ie=UTF8&qid=1328577316&sr=1-2"
	}
new_dvd[5] = {
	id: 		"5",
	title:		"Tangled",
	date:		"29 March 2011",
	image:		"tangled",
	dvd: 		"http://www.amazon.com/Tangled-Mandy-Moore/dp/B004G600A4/ref=sr_1_1?s=movies-tv&ie=UTF8&qid=1328577375&sr=1-1",
	bluray: 	"http://www.amazon.com/Tangled-Two-Disc-Blu-ray-DVD-Combo/dp/B004G6009U/ref=sr_1_2?s=movies-tv&ie=UTF8&qid=1328577375&sr=1-2"
	}
	
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
/*********************************************************************************************************/
